// <auto-generated />
using System;
using MandoWebApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MandoWebApp.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220328112600_Identity-TestUser-Extension")]
    partial class IdentityTestUserExtension
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Duende.IdentityServer.EntityFramework.Entities.DeviceFlowCodes", b =>
                {
                    b.Property<string>("UserCode")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DeviceCode")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("Expiration")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SubjectId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("UserCode");

                    b.HasIndex("DeviceCode")
                        .IsUnique();

                    b.HasIndex("Expiration");

                    b.ToTable("DeviceCodes", (string)null);
                });

            modelBuilder.Entity("Duende.IdentityServer.EntityFramework.Entities.Key", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DataProtected")
                        .HasColumnType("bit");

                    b.Property<bool>("IsX509Certificate")
                        .HasColumnType("bit");

                    b.Property<string>("Use")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Use");

                    b.ToTable("Keys");
                });

            modelBuilder.Entity("Duende.IdentityServer.EntityFramework.Entities.PersistedGrant", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ConsumedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("Expiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SubjectId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Key");

                    b.HasIndex("ConsumedTime");

                    b.HasIndex("Expiration");

                    b.HasIndex("SubjectId", "ClientId", "Type");

                    b.HasIndex("SubjectId", "SessionId", "Type");

                    b.ToTable("PersistedGrants", (string)null);
                });

            modelBuilder.Entity("MandoWebApp.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsTestUser")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "42a760de-497b-44c1-84f0-9388087fc344",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "336f6c3e-701a-4382-a61e-760f0e3f01d2",
                            Email = "volunteer@mandakdb.com",
                            EmailConfirmed = true,
                            IsTestUser = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "VOLUNTEER@MANDAKDB.COM",
                            NormalizedUserName = "VOLUNTEER@MANDAKDB.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEDzZLBzI03iuMONiGUrZxAG9l89XzAp5MPKbzA1Piix1XPKRlC4x+5ZlcHFyTjXjsg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "af93a8f2-c0ba-4b44-a43a-d65bc43fd608",
                            TwoFactorEnabled = false,
                            UserName = "volunteer@mandakdb.com"
                        },
                        new
                        {
                            Id = "ff732cde-8b20-46b3-a698-2da238d80c2d",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d4d63954-822f-44d7-8f5f-dd5754947767",
                            Email = "benefactor@mandakdb.com",
                            EmailConfirmed = true,
                            IsTestUser = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "BENEFACTOR@MANDAKDB.COM",
                            NormalizedUserName = "BENEFACTOR@MANDAKDB.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEGehDWrCpXSzn8caWMHcZMWJQ7hm2lewcwpUR5Ay2n15H7s+Rgn3hp2Wp4N8kI19CA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "cf38b9ff-68f3-4257-b129-d14cbb362544",
                            TwoFactorEnabled = false,
                            UserName = "benefactor@mandakdb.com"
                        },
                        new
                        {
                            Id = "98195404-8874-4ecd-a28e-cba611fa7f88",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7985c0e2-6c28-44fc-b303-198e354abee5",
                            Email = "manager@mandakdb.com",
                            EmailConfirmed = true,
                            IsTestUser = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "MANAGER@MANDAKDB.COM",
                            NormalizedUserName = "MANAGER@MANDAKDB.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEM/smygeqGZ/qxatd1FAEpSgSRa5rvFAhzfXc1A1lSSpkhym2om2kxePJYXb1njFMg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f5f059a2-c6fc-4a33-852a-24a94d20c58e",
                            TwoFactorEnabled = false,
                            UserName = "manager@mandakdb.com"
                        },
                        new
                        {
                            Id = "8d644e3b-3e19-446b-a45a-301a3a0144b7",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "98450eec-b7da-4e55-a044-1e02f5dc270d",
                            Email = "administrator@mandakdb.com",
                            EmailConfirmed = true,
                            IsTestUser = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMINISTRATOR@MANDAKDB.COM",
                            NormalizedUserName = "ADMINISTRATOR@MANDAKDB.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEIUcZIQ4XkTiSq+l/DVMxIQ9lhMYWse7x3VVZkBbY4WHdkwzkiIlAxfd4bDXvyrQVg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f4e33c59-e1da-49ea-8a8d-3fb9f4178494",
                            TwoFactorEnabled = false,
                            UserName = "administrator@mandakdb.com"
                        });
                });

            modelBuilder.Entity("MandoWebApp.Models.Building", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ENDescription")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("EN_Description");

                    b.Property<string>("ENName")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("EN_Name");

                    b.Property<string>("HUDescription")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("HU_Description");

                    b.Property<string>("HUName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("HU_Name");

                    b.Property<int>("Zip")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Building");
                });

            modelBuilder.Entity("MandoWebApp.Models.BuildingProduct", b =>
                {
                    b.Property<int>("BuildingID")
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .HasColumnType("varchar(3)");

                    b.HasKey("BuildingID", "ProductID");

                    b.HasIndex("ProductID");

                    b.ToTable("Map_Building_Product");
                });

            modelBuilder.Entity("MandoWebApp.Models.Invite", b =>
                {
                    b.Property<Guid>("InviteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("InviteId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Invite");
                });

            modelBuilder.Entity("MandoWebApp.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ENName")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("EN_Name");

                    b.Property<string>("HUName")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("HU_Name");

                    b.Property<int?>("SizeType")
                        .HasColumnType("int");

                    b.Property<int>("UnitID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UnitID");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("MandoWebApp.Models.Unit", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("ENName")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("EN_Name");

                    b.Property<string>("HUName")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("HU_Name");

                    b.HasKey("ID");

                    b.ToTable("Unit");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            ENName = "Piece",
                            HUName = "Darab"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "99ed77a4-097d-4175-9ff0-85e583eabe89",
                            ConcurrencyStamp = "e7438c3f-c644-4fcf-aebb-f66c123345ae",
                            Name = "Volunteer",
                            NormalizedName = "VOLUNTEER"
                        },
                        new
                        {
                            Id = "8a8969ac-7762-4637-98bc-228471a240fb",
                            ConcurrencyStamp = "776ae477-4a75-4aaa-8cf7-24f472ad374c",
                            Name = "Benefactor",
                            NormalizedName = "BENEFACTOR"
                        },
                        new
                        {
                            Id = "45115a8a-11f6-4192-83d2-f04b3e3fd0bb",
                            ConcurrencyStamp = "6923d565-7496-4c75-91d9-848aed4c7ffd",
                            Name = "Manager",
                            NormalizedName = "MANAGER"
                        },
                        new
                        {
                            Id = "6439468e-28bc-4d50-bf26-e4e3bb93bbbb",
                            ConcurrencyStamp = "b925cfd5-3307-4c02-9182-d6a3dda4709c",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "42a760de-497b-44c1-84f0-9388087fc344",
                            RoleId = "99ed77a4-097d-4175-9ff0-85e583eabe89"
                        },
                        new
                        {
                            UserId = "ff732cde-8b20-46b3-a698-2da238d80c2d",
                            RoleId = "8a8969ac-7762-4637-98bc-228471a240fb"
                        },
                        new
                        {
                            UserId = "98195404-8874-4ecd-a28e-cba611fa7f88",
                            RoleId = "45115a8a-11f6-4192-83d2-f04b3e3fd0bb"
                        },
                        new
                        {
                            UserId = "8d644e3b-3e19-446b-a45a-301a3a0144b7",
                            RoleId = "6439468e-28bc-4d50-bf26-e4e3bb93bbbb"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MandoWebApp.Models.BuildingProduct", b =>
                {
                    b.HasOne("MandoWebApp.Models.Building", null)
                        .WithMany("BuildingProducts")
                        .HasForeignKey("BuildingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MandoWebApp.Models.Product", null)
                        .WithMany("BuildingProducts")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MandoWebApp.Models.Product", b =>
                {
                    b.HasOne("MandoWebApp.Models.Unit", null)
                        .WithMany("Products")
                        .HasForeignKey("UnitID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MandoWebApp.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MandoWebApp.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MandoWebApp.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MandoWebApp.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MandoWebApp.Models.Building", b =>
                {
                    b.Navigation("BuildingProducts");
                });

            modelBuilder.Entity("MandoWebApp.Models.Product", b =>
                {
                    b.Navigation("BuildingProducts");
                });

            modelBuilder.Entity("MandoWebApp.Models.Unit", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
