services:
  app:
    image: mando:latest
    container_name: mando-app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - Db__Server=db
      - Db__Port=3306
      - Db__Database=mando
      - Db__Uid=app
      - Db__Password=pwd

  db:
    image: mariadb:10.7
    container_name: mando-db
    environment:
      #- MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=mando
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pwd
